# Generated by Django 3.1.7 on 2021-06-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_owner_name', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact_no', models.IntegerField()),
                ('home_delievery', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
        ),
    ]
